// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMSZPt0y-8QN70CEqo2210gWye44tjbDU',
    appId: '1:785631059008:web:0dc5c1cff46236d59793a5',
    messagingSenderId: '785631059008',
    projectId: 'ardennes-85ab2',
    authDomain: 'ardennes-85ab2.firebaseapp.com',
    storageBucket: 'ardennes-85ab2.appspot.com',
    measurementId: 'G-81LX066PD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmlm_g9yhEwGskp5P0DVoidzYRchJC7no',
    appId: '1:785631059008:android:45f7b560830954db9793a5',
    messagingSenderId: '785631059008',
    projectId: 'ardennes-85ab2',
    storageBucket: 'ardennes-85ab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyOGOFAV2HGtBzTjLDag5bSu69QH0I8VY',
    appId: '1:785631059008:ios:10dc6241200835219793a5',
    messagingSenderId: '785631059008',
    projectId: 'ardennes-85ab2',
    storageBucket: 'ardennes-85ab2.appspot.com',
    iosBundleId: 'com.ripplearc.ardennes.ardennes',
  );
}
